D_LİST = [
	"Telefonunda en son aradığın şey neydi?","Birisi kız arkadaşın / erkek arkadaşından ayrılmak için sana 1 milyon tl önerseydi, yapar mıydın?",
	"Bu grupda en az kimi seviyorsun ve neden?","Hiç sınıfta yüksek sesle geğirdin mi?",
	"Hiç sınıfta yüksek sesle geğirdin mi?","Yerden bir şeyi alıp hiç yedin mi?",
	"Bir gün karşı cins olarak uyanırsan, ilk yapacağın şey nedir?",
	"Hiç havuzda işedin mi?","Asansörde hiç gaz kaçırdın mı?",
	"Tuvalette otururken aklınıza gelen şeyler nelerdir?","Büyüyen hayali bir arkadaşınız var mıydı?",
	"En kötü alışkanlığınız nedir?","Burnunu karıştırır mısın?","Banyoda şarkı söyler misin?",
	"Hiç üzerine işedin mi?","Toplumda en utanç verici anınız neydi?","Aynada kendinle hiç konuştun mu?",
	"Web geçmişinizi, birileri görürse utanacağınız şey ne olurdu?","Uykunda konuşur musun?",
	"Gizli aşkın kim?","Benim hakkımda neyi sevmiyorsun?","Şu an ne renk iç çamaşır giyiyorsun?",
	"Son attığın mesaj neydi?","İnsanları yanan bir binadan kurtarıyor olsaydınız ve bir kişiyi bu grupdan geride bırakmak zorunda kalırsanız, kim olurdu?",
	"İç çamaşırlarını ne sıklıkla yıkıyorsun?","Hiç kulak kiri tattın mı?",
	"Hiç osurup başka birini suçladın mı?","Hiç terinin tadına baktın mı?",
	"Bu odadaki kim bugüne kadarki en kötü insan olurdu? Neden?",
	"Yeniden doğmuş olsaydın, hangi yüz yılda doğmak isterdin?","Söylediğiniz veya yaptığınız bir şeyi silmek için zamanda geriye gidebilseydiniz, bu hangi yıl olurdu?",
	"Erkek arkadaşın veya kız arkadaşın seni hiç utandırdı mı?","Birdenbire görünmez olsaydın ne yapardın?",
	"Banyoda kaldığınız en uzun süre nedir ve neden bu kadar uzun süre kaldınız?","Şimdiye kadar gördüğüm en garip rüyayı anlat.",
	"Duşta işiyor musun?","Hala yaptığın en çocukça şey nedir?","Hangi çocuk filmini tekrar tekrar izleyebilirsin?",
	"Ayak kokunuz kötü mü?","Saçma takma adların var mı?","Telefonunuzda hangi uygulamada en çok zaman harcıyorsunuz?",
	"Tek bir oturuşta yediğin en çok yemek ne?","Tek başınayken dans ediyor musun?","Karanlıktan korkar mısın?",
	"Bütün gün evdeysen ne yapardın?","Günde kaç öz çekim yapıyorsunuz?","En son ne zaman dişlerini fırçaladın?",
	"En sevdiğin pijamalar neye benziyor?","Hiç yerden bir şey yedin mi?","Yapmaman gereken bir şeyi yaparken hiç yakalandın mı?",
	"Vücudunun hangi bölümünü seviyorsun, hangi kısmından nefret ediyorsun?","Hiç bitlendin mi?",
	"Pantolonunu hiç kestin mi?","Tabağını yalıyor musun?","Kimsenin senin hakkında bilmediği bir şey nedir?",
	"Hiç tabağını yaladın mı?","Dirseğini yalayabilir misin?","Eğer buradaki herkesi yanan bir binadan kurtarmaya çalışıyor olsaydın ve birini geride bırakmak zorunda kalırsan, kimi geride bırakırdın?",
	"Telefonda aradığın son şey neydi?","Bir uygulamayı telefonunuzdan silmek zorunda kalsanız hangisini silerdiniz?","Bir ilişkideki en büyük korkun nedir?",
	"Odanın her bir kişi hakkında bir tane olumlu, bir tane olumsuz şey söyleyin.","Sevmediğin kötü huyun var mı?",
	"Hayatında yaptığın en çılgın şey nedir?","Üç gün boyunca bir adada mahsur kalmış olsaydınız, bu grupdan kimleri seçerdiniz?",
	"Bu odadaki en sinir bozucu kişi kim?","Bu grupdan biriyle evlenmek zorunda kalsan kim olurdu?","En uzun ilişkiniz ne kadar sürdü?",
	"Bir ünlü Instagram’da seni takip etseydi bu ünlünün kim olmasını isterdin?","Instagram’da 5 kişiyi silmek zorunda olsan kimleri silerdin?",
	"Kaç çocuk sahibi olmak istersin?","Hayallerinizdeki kişiyi tarif edin.","Messi mi Ronaldo mu?","Pes mi Fifa mı?",
	"İlk işin neydi?","Üniversite hakkındaki en büyük korkun nedir?","En iyi arkadaşının seninle aynı üniversiteye gitmesini ister misin?",
	"Mevcut erkek arkadaşının ya da kız arkadaşının seninle aynı üniversiteye gitmesini ister misin?","Hayalindeki iş ne?",
	"Hiç bir dersten başarısız oldun mu?","Hiç kopya çektin mi?","Hiç sınıfta uyudun mu?","Sınıfta asla yanında oturmak istemeyeceğin kim?",
	"Derse hiç geç kaldın mı?","Bir öğretmenin önünde yaptığın en utanç verici şey nedir?","Hiç masanın altına sakız attın mı?",
	"Hiç okulda kavga ettin mi?","Bir sınavdan aldığın en kötü puan neydi?","Sınıfta hiç uyuya kaldın mı?","Hiç gözaltına alındın mı?",
	"Eğer görünmez olsaydın hangi derse gizlice girerdin?","En kötü grup hangisidir?","Bu grupdaki sır tutma  konusunda en çok zorlanan kişi kimdir?",
	"Söylediğin en son yalan neydi?","Spor yapar mısın?","Hayatının geri kalanında sadece bir kıyafet giyebilseydin, bu kıyafetin hangi renk olurdu?",
	"Sizce Türkiye’nin eğitim sisteminde yapılması gereken en önemli değişiklik nedir?","Karanlıktan/yükseklikten korkar mısın?",
	"Kendi görünuşünü 1 ile 10 arasında puanla :)","Yaptıgın en yasadışı şey neydi?","Şimdi sana bir evlenme teklifi gelse ve sevmediğin biri olsa, ve bu sana son gelecek evlilik teklifi olsa kabul edermiydin?",
	"Şu anki ruh haline bakarak ne tür film izlersin (aksiyon/dram/bilim kurgu/romantik komedi/biyografi/fantastik)",
	"Kendini en ezik hissettiğin an hangisiydi ?","ilerde çocuğun olursa ne isim koymak istersin?",
	"Unicorun mu olmasını isterdin ejderhan mı?","Kaç sevgilin oldu?","Hayatta unutmadığın biri var mı?",
	"en sevdiğin şarkı?","Yapmaman gereken bir şeyi yaparken hiç yakalandın mı?","En sevdiğin sanatçı kim?",
	"karşı cinste ilk dikkatini çeken ne?","bu yıl hayatında neyi değişmeyi uygun görüyorsun?",
	"Birinin telefonunda gördüğün en tuhaf şey nedir?","Süper kahramanlar gerçekten var olsaydı Dünya nasıl bir yer olurdu?",
	"Hayatın size öğrettiği en önemli ders nedir?","Kültürümüzün en çok sevdiğiniz yanı nedir?","Ailenizin uyguladığı en tuhaf gelenek nedir?",
	"Aileniz dışında, yaşamınız üzerinde en büyük etkisi olan kişi kimdir?","Kadın/Erkek olmanın en kötü ve en iyi yanı nedir?",
	"Beynini bir robota yerleştirebilir ve sonsuza kadar bu şekilde yaşayabilsedin,bunu yapar mıydın?","Evinizde ağırladığın en kötü misafir kimdi ve ne oldu?",
	"İnsanların size ne sormasından bıktınız?","En tuhaf korkunuz nedir?","En sevdiğiniz TV programı hangisidir?","Girdiğiniz en saçma tartışma nedir?",
	"En son söylediğin yalan nedir?", "Biriyle çıkarken yaptığın en utanç verici şey neydi?",
	"Hiç arabanla (varsa) yanlışlıkla bir şeye birine çarptın mı?",
	"Hoşuna gittiğini düşündüğün ama bir türlü açılamadığın biri oldu mu?","En tuhaf takma adın nedir?",
	"Fiziksel olarak sana en acı veren deneyimin ne oldu?","Hangi köprüleri yakmak seni rahatlattı?",
	"Toplu taşıma araçlarında yaptığın en çılgınca şey neydi?","Şişeden bir cin çıksa üç dileğin ne olurdu?","Dünyadaki herhangi birini Türkiye’nin başkanı yapabilseydin bu kim olurdu?",
	"Şimdiye kadar bir başkasına söylediğin en acımasızca şey neydi?","Birini öperken kendini hiç kötü hissettin mi?","Hiçbir sonucu olmayacağını bilsen ne yapmak isterdin?",
	"Bir aynanın önünde yaptığın en çılgınca şey nedir?","Şimdiye kadar başkasına söylediğin en anlamlı şey neydi?",
	"Arkadaşlarınla yapmayı sevdiğin ama sevgilinin önünde asla yapmayacağın şey nedir?","Bu hayatta en çok kimi kıskanıyorsun?",
	"En sevdiğin pijamaların neye benziyor?","Bir buluşmadan kaçmak için hiç hasta numarası yaptın mı?","Çıktığın en yaşlı kişi kim?",
	"Günde kaç tane özçekim yaparsın?","Aşk için her şeyi yaparım ama “bunu” yapmam dediğin şey nedir?","Haftada kaç kez aynı pantolonu giyiyorsun?",
	"Bugün şansın olsa lise aşkınla çıkar mısın?","Vücudunun hangi bölümlerinden gıdıklanıyorsun?",
	"Çeşitli batıl inançların var mı? Varsa onlar neler?","Sevdiğini itiraf etmekten utandığın film hangisidir?","En utan verici kişisel bakım alışkanlığın nedir?","En son ne zaman ve ne için özür diledin?","Sözlü destanlar hakkında ne düşünüyorsun?",
	"Utanç verici kokularınızın çoğu nereden geliyor?","Hiç sevgilini anlatmayı düşündün mü?","Hiç sevgilini biriyle aldattın mı?","Boxer mı yoksa külot mu?","Hiç havuza veya denize işedin mi?","Saçlarını uzatmayı düşünsen ne kadar uzatırdın?","Kimsenin bilmeyeceği garanti olsa kimi öldürmek isterdin?","Başkası için aldığın en ucuz hediye nedir?",
	"Zamanının çoğunu en çok hangi uygulamada harcıyorsun?","Otobüste yaptığın en tuhaf şey nedir?","Hiç toplum içinde çıplak kaldın mı?","Günde ne kadar dedikodu yaparsın?","Çıkmak isteyeceğin en genç kişi kaç yaşında olurdu?","Hiç toplum içindeyken burnunu karıştırdın mı?",
	"Hiç yaşın hakkında yalan söyledin mi?","Telefonundan bir uygulamayı silmek zorunda olsan bu hangisi olurdu?",
	"Gece geç saatte yaptığın en utanç verici şey nedir?","Duş almadan en uzun süre ne kadar durdun?","Hiç sahte kimlik kullandın mı?","Kırmızı halıda beraber yürümek istediğin ünlü isim kim?","Gizli aşkın kim?"
]

S_LİST = [
        "Şimdiye kadar öpüştüğün en iyi kişi kim?","Hiç biriyle seks yaptın mı?","Hiç birine nude fotoğraf gönderdin mi?","Hiç hemcinsinden etkilendin mi?","En büyük cinsel fantezin nedir?",
        "Çıplak uyumayı sever misin?","Tinderdan buluştuğun biriyle hiç öpüştün mü?","Biriyle beraber olmak istesen bu ne olurdu?","İnternette hiç uygunsuz bir şey aradın mı?","Ateşli bir ilişki mi yoksa sakin bir ilişki mi tercih edersin?",
        "Partnerin ile seviştiğin en sıradışı mekan neresi?","Pişmanlık duyduğun bir deneyimin oldu mu?","Ön sevişme esnasında en çok hoşuna giden şey nedir?","Şimdiye kadar en çok keyif aldığın deneyimin hangisiydi?","En sevdiğin pozisyon hangisi?","En çok nerene dokunmaktan hoşlanırsın?",
        "Karşı cins olarak uyansan yapacağın ilk edepsiz şey ne olur?","Hiç tek gecelik ilişki yaşadın mı?","Gerçekten de başına gelen en çılgın fantezin nedir?","Daha önce hiç seninle aynı cinsiyetten biriyle denemeler yaptın mı?","Gizli ve kimsenin bilmediği bir fantezin var mı, fantezin nedir?",
        "Bakire misin?","Seks yaptığın en tuhaf mekân neresiydi?","Yaptığın en çapkınca şey nedir?","Daha önce hiç seksi bir fotoğraf çekmeye çalıştın mı?","Daha önce aynada öpüşmeyi denedin mi?","Okulda öğretmeninle ilgili fantezi kurdun mu?","Hayatın boyunca kaç cinsel partnerin oldu?","En çılgın seks fantezin var mı? Varsa anlat", 
        "Yataktayken başına gelen en ilginç ve utanç verici olayını anlat.","Asla yapmam dediğin bir cinsel aktivite varmı? Varsa anlat.","Başka çiftlerin seks yaptığına şahit oldun mu?","İlk seks deneyimin oldumu olduysa anlat.","Partnerinle beraber duşa girmek ister misin?","İlişkide cinsellik olmadan aşk olur mu?","İş veya okul hayatında gizli sevişmelerin oldu mu?", 
        "Erken boşalma sorunun var mı?","Telefonunda başkasının çıplak fotoğrafı var mı?","Hiç tanımadığın biriyle beraber yattın mı?","Bakireliğini ne zaman kaybettin?","Kendini seksi buluyor musun?","Yalamaktan hoşlandığın 3 şeyi söyle.","İlk cinsel eğitimini kimden, nasıl aldın?","En komik ve ilginç cinsel merakını açıkla.","Seks yaparken ışıkları açık mı, kaplı mı tercih edersin?", 
        "Yaptığın ve bir daha asla yapmayacağın cinsel ilişki hangisi?","En son ne zaman masturbasyon yaptın?","Seks yaparken müzik dinlemekten hoşlanır mısın?","Birinin sana söylediği en seksi şeyler neler?","Duşta masturbasyon yapıyor musun?","En son ne zaman pornografik izledin?","Hiç seks yaparken yakalandın mı?","Mastürbasyon yapmaya ne zaman başladın ve nasıl?","Hiç mastürbasyon yaparken yakalandın mı?", 
        "Sadece sıfatlar kullanarak cinselliğini nasıl tarif edersin (eğlenceli,kabarık, yumuşak, vb.)?","Penisin ya da vajinan olsa ilk ne yapardın?","Bugüne kadar cinsellik hakkında düşüncen nedir ?","Ailen, cinselliğini biliyorsa, nasıl tepki verdiler?","En iyi arkadaşın cinsel hayatın hakkında bir şey biliyor mu? Nasıl tepki verdiler?","Vücut kıllarınla ( koltuk altları, bacaklar vb.) Ne yapıyorsun?",
        "Mastürbasyon yaparken hep hayal kurar mısın?","Hayal kurduğunda genellikle mastürbasyon yapar mısın?","Başka birini hayal ederken, birisiyle seks yaptın mı?","En seksi fantezini tanımlayın.","(Vajina sahipleri) Boşalırken hiç fışkırıyor musun?","Cinsel organına dokunmadan orgazm olabilir misin?","Cinsel organına nasıl dokunulmasından hoşlandığını açıkla","Meme uçların ne kadar hassas? Meme ucunla oynar mısın?", 
        "Başka bir kişiyle ya da mastürbasyon yoluyla orgazm yapmayı daha kolay buluyor musun?","Hard  veya soft bir temastan hangisiyle daha kolay boşalırsın?","Sahip olduğun en iyi orgazm hangisi?","Oral seks yapmaktan hoşlanıyor musun? Hoşlanıyorsan sebebini açıkla","Sözlü olarak almak için en sevdiğiniz pozisyon nedir?","Yaptığın en kötü sextingi tarif et.","Sex sırasında sarılmaktan hoşlanıyor musunuz?",
        "Seks hayatınız nasıl gidiyor?  Sen Hangi Cinsel Fanteziye Daha Yatkınsın?","En son yaptığımız sex te neyi çok beğendin ?","Sexten sonra pişman lık duyuyor musun ?","Seviş me sırasında kendini mi yoksa partnerinin mi daha fazla zevk almasını istersin ?","Yatağa girdiğinde en çok kimi hayalini kurar onunla anı yaşarsın?","Ön sevişmeyi kaç dakika ya kadar yapabilirsin ?"
] 
